export default [
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
  {
    goodId: 'hsdfadkfje23123sakdfj',
    img: '',
    name: 'LM2938IMPX-5.0/NOPB',
    brand: 'a',
    specification: 'Final Product change Notification',
    pictureGroups: 1,
    hasDetected: true,
  },
];
